#!/bin/bash

function description
{
        echo -e "\t<USAGE of filteringShortPeaks>"
        echo -e "\t: It will remove bed intervals that smaller
        than user-defined threshold\n"
        echo -e "\t[filteringShortPeaks -t <threshold> -i <input> -o <output>]"
}

while [ -n "$1" ]
do
    case $1 in

    -h)
        description
        exit 1
        ;;
    -t)
        echo "Threshold is $2"
        inputT=$2
        shift 2
        ;;

    -i)
        echo "Input is $2"
        input=$2
        shift 2
        ;;
    -o)
        echo "Output is $2"
        output=$2
        shift 2
        ;;
    *)
        echo "you used wrong options $1"
        description
        exit 1
        ;;
esac
done


if [ $? != 0 ]; then usage; fi

# Remove peaks that have interval smaller than threshold value.
awk -v threshold=$inputT 'BEGIN {FS="[\t]"}; {if(($3-$2)>threshold) {print $0}}' $input > $output
